### ISSUE TITLE
Unable to compile; no valid source files were found

### ISSUE THREAD

**Issue by kaona** [andismith/grunt-responsive-images#100]
Hi Folks,

I believe I have properly installed Grunt and its dependencies(though I may not have)

When i run grunt in my project folder, I am getting the following error regarding not finding files in the source folder. The path seems properly formatted to me. Anything standout to you? Thank you.
,,,

    Kaona (master *) kaona.github.io $ grunt
    Running "responsive_images:dev" (responsive_images) task
    >> Unable to compile; no valid source files were found.
    >> Unable to compile; no valid source files were found.
    
    Done, without errors.

,,,

My Gruntfile.js file is in the project folder root same as package.json.
This is my Gruntfile:

    'use strict';
    
    module.exports = function(grunt) {
    
      grunt.initConfig({
        responsive_images: {
          dev: {
            options: {
              sizes: [{
                name: 'small',
                width: '30%',
                suffix: '_small',
                quality: 20
              },{
                name: 'large',
                upscale:true,
                width: '50%',
                suffix: '_large',
                quality: 40
              }]
            },
            files: [{
              expand: true,
              src: ['img/**.{gif,jpg,png}'],
              cwd: 'images/',
              dest: 'images/'
            }]
          }
        },
      });
    
      grunt.loadNpmTasks('grunt-responsive-images');
      grunt.registerTask('default', ['responsive_images']);
    
    };
    ,,,

package.json is in same project root directory and follows here in part:

     {
      "name": "kaona.github.io",
      "version": "1.0.0",
      "description": "udacity project 4",
      "main": "gruntfile.js",
      "dependencies": {
        "grunt": "^0.4.5",
        "grunt-responsive-images": "^0.1.7"
      },
      "devDependencies": {
        "grunt-responsive-images": "^0.1.7"
      },

Source files are here:
![screen shot 2015-10-31 at 10 06 56](https://cloud.githubusercontent.com/assets/2370391/10864067/ce58894a-7fb7-11e5-933a-4a7b61c0f9f7.png)

**Comment by andismith** [comment]
You have cwd as 'images/' but there is no images folder as far as I can see.

**Comment by mau-ferrusca** [comment]
What are the differences between "cwd" and "src", then?

**Comment by andismith** [comment]
Any path in cwd is not appended to the dist path.
Any path in src is appended to the dist path.

More info:
http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by mau-ferrusca** [comment]
Excellent. I had not reached that part of the documentation. Only question that remains is what does "cwd" stand for?

Thanks, Andi.

**Comment by andismith** [comment]
Current Working Directory

Can I close this issue now please?

**Comment by mau-ferrusca** [comment]
By all means, thank you.

On Mon, Dec 7, 2015 at 9:41 AM, Andi Smith <notifications@github.com> wrote:

> Current Working Directory
>
> Can I close this issue now please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andismith/grunt-responsive-images/issues/100#issuecomment-162561601>
> .
>



-- 

Front End Senior Web Developer <https://mx.linkedin.com/in/mauricioferrusca>

HTML5, CSS, jQuery, Javascript

Co-Founder at codificARTE <http://codificarte.com.mx>

Twitter: @MauFerrusca

**Comment by andismith** [comment]
Your welcome :)
