### ISSUE TITLE
problem with too many images

### ISSUE THREAD

**Issue by slimzc** [andismith/grunt-responsive-images#106]
Hi Andi, I'm using responsive-images with some 2430 files (.jpg) . Now, I try to add some new image and get this message:

Warning: Command failed: convert: unable to open image `adaptative-images/common/images/skus/marca/test2.5-listado.jpg': Permission denied @ error/blob.c/OpenBlob/2588.

It's a problem with some limit? because I have all permission over the file.
Please, let me know if you have some advice for this situation.
Regards!

**Comment by slimzc** [comment]
Hi, I try to change de engine to GraphicsMagicks but now i get this error: 

arning: Command failed: gm identify: No decode delegate for this image format (src/skus/Burton/test2.5.jpg).
gm identify: Request did not return an image.
 Used --force, continuing.
Fatal error: Cannot call method 'trim' of undefined
TypeError: Cannot call method 'trim' of undefined
    at gm.<anonymous> (/apps/responsive-images/node_modules/grunt-responsive-images/tasks/responsive_images.js:322:34)
    at gm.<anonymous> (/apps/responsive-images/node_modules/gm/lib/getters.js:164:25)
    at cb (/apps/responsive-images/node_modules/gm/lib/command.js:264:16)
    at ChildProcess._spawn.proc.on.onExit (/apps/responsive-images/node_modules/gm/lib/command.js:246:9)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by andismith** [comment]
I haven't come across a limit, but I'll admit I haven't reached the large number of files you appear to have reached. Have you tried temporarily changing your configuration to only change test2.5-listado.jpg and see if it works? That would help indicate if it's an image problem or something else. You could also try splitting your images in to two tasks (I'm presuming they are not all in the same folder).

As a side note, 2430 images must take some time to process - do you need to process them all each time?

**Comment by andismith** [comment]
There's been no update to this issue in some time. Previously we spoke about whether all these images need processing at the same time, and we've now introduced concurrency that could help.

Closing. Please reopen if you still consider this an issue.
