### ISSUE TITLE
Deprecated Dependencies

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [andismith/grunt-responsive-images#110]
The library lodash is coded as a dependency in package.json, but the version number needs to be updated to ~4.6.1

lodash has been upgraded since this plugin was written, and needs to be changed to a more recent version

**Comment by deadmantfa** [comment]
+1

**Comment by superclarkk** [comment]
+1 Pleeaaaasee!!!

**Comment by superclarkk** [comment]
+1

**Comment by andismith** [comment]
Done, thanks
