### ISSUE TITLE
_ instead of -

### ISSUE THREAD

**Issue by sbuisson** [andismith/grunt-responsive-images#113]
you should create an alias task responsive**-**images(tiret) who redirect on the  responsive**_**images(underscore) task.

**Comment by andismith** [comment]
Thanks for the suggestion. But why?

**Comment by sbuisson** [comment]
Sorry, I did'nt see your first message.
It's juste that the name is very confusing: by convention , we don't use _ in the task name, but - . And this type of name mistake is very hard to find.
