### ISSUE TITLE
Jimp support

### ISSUE THREAD

**Issue by ArmorDarks** [andismith/grunt-responsive-images#119]
Hi

First of all, thanks for great task! We're happy to use it in [Kotsu](https://github.com/LotusTM/Kotsu/tree/release/1.0.0) for quite a while.

It seems that finally Node community got alternative for external dependencies like GraphicsMagick or ImageMagick in form of [Jimp](https://github.com/oliver-moran/jimp)

Are there any chances to see support of it?

**Comment by andismith** [comment]
If there's interest in support for this, sure. Please let me know by upvoting this issue!

I'm not sure if Jimp has all the features we currently support though?

**Comment by ArmorDarks** [comment]
> I'm not sure if Jimp has all the features we currently support though?

Can't tell for sure for now, have to study it closer. However, I'm quite doubtful that it will ever support all GM features, but set of current features should be enough. 

Most important, a lot of people will trade off some non-crucial features for absence of need to install external dependency.

**Comment by andismith** [comment]
JIMP doesn't support GIFs. How do people feel about this?

**Comment by ArmorDarks** [comment]
We didn't use in our projects gif for years (png FTW), but I think some people might be upset with it. 

Jimp could be regarded only as alternative engine, since it's anyway not as powerful as GraphicsMagick. Though, in most project nobody will need all capabilities of GraphicsMagick.

However, I have some concerns about well being of Jimp. During last month there were very little development in their repository...

**Comment by ArmorDarks** [comment]
There seems to be js implementation of gif encoder/decoder called [omggif](https://github.com/deanm/omggif), so I've opened issue about it in Jimp repo. Maybe eventually Jimp will get gif support too.

Ref https://github.com/oliver-moran/jimp/issues/166

**Comment by andismith** [comment]
Please consider using https://www.npmjs.com/package/grunt-jimp for JIMP support

**Comment by ArmorDarks** [comment]
Not exactly what I meant.

`grunt-jimp` isn't that good adapted for image scaling and related to it nice features. But whatever :)
