### ISSUE TITLE
Deprecated minimatch and graceful-fs

### ISSUE THREAD

**Issue by hannwong** [andismith/grunt-responsive-images#121]
### Expected Behaviour

No use of deprecated packages.
No warnings issued regarding use of deprecated packages.

In particular, note that graceful-fs is clearly indicated to be too old for node >= v7.0.

### Actual Behaviour

2 warnings for minimatch. 1 for graceful-fs.

    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

### Steps to Reproduce

`npm install grunt-responsive-images'

### PC/Mac and Graphics Engine used

N.A.

### Grunt Configuration

    "devDependencies": {
        "grunt": "^1.0.1",
        "grunt-cli": "^1.2.0",
        "grunt-responsive-images": "^0.1.9"
    }

node v7.1.0

**Comment by andismith** [comment]
It looks like this is an issue with Grunt itself as GRI doesn't depend on these packages directly.
See: https://github.com/gruntjs/grunt/issues/1557 and https://github.com/gruntjs/grunt/issues/1467

The plugin does however have a dependency on an older version of Grunt, so I will update this to a newer version.

Thanks for reporting.

**Comment by andismith** [comment]
I've released a new version, see if that fixes it?

**Comment by hannwong** [comment]
> It looks like this is an issue with Grunt itself

Yikes!

Sorry for wasting your time! No issue here.

**Comment by andismith** [comment]
Thanks for the feedback.
