### ISSUE TITLE
Could Not Execute Graphics Magick

### ISSUE THREAD

**Issue by guti7** [andismith/grunt-responsive-images#130]
### Expected Behaviour
Perform task: `grunt responsive_images`

### Actual Behaviour
```
Warning: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%m:%T:%s" "images/cockatoos.jpg" this most likely means the gm/convert binaries can't be found Use --force to continue.

Aborted due to warnings.
```

### Steps to Reproduce
Command line: `grunt responsive_images`

### PC/Mac and Graphics Engine used
macOS 10.13.3
ImageMagick 7.0.7-22

### Grunt Configuration
```
    responsive_images: {
      dev: {
        files: [{
          expand: true,
          cwd: 'images/',
          src: ['**/*.{jpg,gif,png}'],
          dest: 'build/images/'
        }]
      }
    }
```

### Comments
It appears it is not detecting that I have ImageMagick installed. I do not have GraphicsMagick installed.

**Comment by guti7** [comment]
#130
### Comments Edit
I meant to say ImageMagick 7.0.7-22 is installed and GraphicsMagick is not installed.

According to installation in [README.md](https://github.com/andismith/grunt-responsive-images#getting-started) you need either one, not indicating that both are required.

**Comment by fontsie** [comment]
You can use only one engine! Default one is GraphicsMagick, if you want use ImageMagick you must set 'options.engine' to 'im'.

see: https://github.com/andismith/grunt-responsive-images/blob/master/README.md#options
