### ISSUE TITLE
Keep aspect ratio

### ISSUE THREAD

**Issue by Gijsjan** [andismith/grunt-responsive-images#25]
Could there be an option to keep the aspect ratio in tact?

**Comment by leewillis77** [comment]
Hi; 

I'm wondering whether this needs re-opened. The behaviour I'm trying to achieve is pretty well described by https://github.com/andismith/grunt-responsive-images/issues/25#issuecomment-29795240. 

I'd like to specify an absolute width and height, and have the source image scaled such that no part of the image is cropped (E.g. max dimension is scaled down), but the image has the specified width and height. 

For example, if an image 640x320 is resized to 64x64, I'd want to get a 64x64 image back where the source image occupies a 64x32 area across the centre of the final image. 

@andismith's comment above suggests this is possible with the current release, but I can't see how. 

I believe adding:
```-gravity "Center" -background "rgba(255,255,255,0)" -extent 32x32```
to the command line achieves what I'm after, but I can't see any way to pass those extra args in either.

Does this need re-opened? A new issue? Just documentation?

I'm no JS-whizz so unlikely to be able to help with a PR unless it's documentation related, but all feedback welcome.
