### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by paallaire** [andismith/grunt-responsive-images#37]
Is possible not have the width in the name of the file ?

Example:

Image:
main-feature.jpg

Result l have (not good)
main-feature-50.jpg
main-feature-100@2x.jpg

Result ( what l want )
main-feature.jpg
main-feature@2x.jpg

Source:
grunt.initConfig({
  responsive_images: {
    myTask: {
      options: {
				units: { percentage: '', pixel: '', multiply: '' },
        sizes: [{
					name: '',
          width: '50%',
					aspectRatio: true,
					quality: 100
        },
        {
					name: '',
          width: '100%',
					aspectRatio: true,
					quality: 100,
					suffix: '@2x'
        }	],
      },
      files: [{
        expand: true,
        cwd: 'retina/',
        src: ['**/*.{jpg,gif,png}'],
        dest: 'tmp/'
      }]
    }
  },
})

**Comment by andismith** [comment]
Closing as 2 years old and this is supported by aforementioned PR.
