### ISSUE TITLE
Command failed: gm convert: Pixel cache allocation failed

### ISSUE THREAD

**Issue by craigmdennis** [andismith/grunt-responsive-images#56]
Working this into my responsive workflow and suddenly this error occurs. Not sure if it's related to GraphicsMagik or not.

`Command failed: gm convert: Pixel cache allocation failed`.
It sounds like I ran out of RAM but I have 5GB still available.

Running Mac OSX `10.9.4`
Grunt version `0.4.5`
Responsive Images `0.1.3`
Image dimensions are `1648x2048`

Here is the grunt task:

```
// Resize images for SRCSET
    responsive_images: {
      options: {
        upscale: false,
        sizes: [{
          width: 320
        },{
          name: '320',
          width: 640,
          suffix: '@2x' // Fallback
        },{
          width: 480
        },{
          width: 640
        },{
          width: 960,
        },{
          width: 1280,
        }]
      },
      dist: {
        files: [{
          expand: true,
          cwd: '<%= config.app %>/',
          src: ['images/{,*/}*.{gif,jpeg,jpg,png}'],
          dest: '.tmp/'
        }]
      },
    },
```

**Comment by olalonde** [comment]
I had the same issue with node gm: https://github.com/aheckmann/gm/issues/598

It was also a file with `.jpg` extension but detected as a photoshop document with `file`. Possibly related: http://www.imagemagick.org/discourse-server/viewtopic.php?t=28371
