### ISSUE TITLE
Process newer / changed images only

### ISSUE THREAD

**Issue by garygreen** [andismith/grunt-responsive-images#57]
I notice across the issues that a number of guys would like to see this and @andismith has pointed out the [Grunt Newer](https://www.npmjs.org/package/grunt-newer) plugin however it's unfortunate that using newer doesn't work, as it's not always a one fit-solution. For instance, response-images uses a non-standard way of specifying the `src` and `dest` as in this example (which newer quite heavily relies on)

```
grunt.initConfig({
  responsive_images: {
    myTask: {
      options: {},
      files: {
        'dest/mario-yoshi.jpg': 'test/assets/mario-yoshi.jpg'
      }
    }
  }
})
```

Also in the instance of using [custom options](https://github.com/andismith/grunt-responsive-images#custom-options) newer can only [handle basic string matching in a specific format](https://github.com/tschaub/grunt-newer/blob/master/tasks/newer.js#L69). You can currently specify a number of wildcards and special `{%= =%}` parameters which newer knows nothing about.

Even with a pull request to the newer plugin (possibly to support the most basic first example), it still wouldn't support the full range of parameters this plugin offers. Therefore a custom inbuilt solution is likely needed and would be an incredible feature to have in the core.

**Comment by laurentvd** [comment]
Any updates on this topic? The newFilesOnly: true option does just what it says. It ignores existing images that are updated. I've tried to use it with the grunt-newer module, but that doesn't seem to work as expected. For now it is kind of blocking our workflow as we need to clean our destination folder every time one of the images if update. I'd be willing to make a PR, if you can give me some directions on where to start.

**Comment by ArmorDarks** [comment]
Hi @andismith!

For some reason `grunt-newer` indeed doesn't work with Responsive Images, even despite we do not use any fancy `{%= =%}` parameters:

```coffee
  @config 'responsive_images',
    thumbnails:
      options:
        separator: '@'
        sizes: [
          width: 240
        ]
      files: [
        expand: true
        cwd: '<%= path.source.images %>'
        src: '{,**/}*.{jpg,jpeg,gif,png}'
        dest: '<%= path.build.images %>'
      ]
```

So it seems that Responsive Images using not-so-standard for Grunt paths, otherwise Newer would be able to pick changes.

Any chances that issue will be resurrected after few years? :)

**Comment by ArmorDarks** [comment]
@garygreen I wonder, did you resolve issue somehow, or just gave up?
