### ISSUE TITLE
large file sizes for pngs

### ISSUE THREAD

**Issue by nwtn** [andismith/grunt-responsive-images#63]
The PNGs output by grunt-responsive-images are consistently larger in file size than when I save from Photoshop. This is a problem, since responsive images are all about delivering improved performance.

For example: I started with a source PNG that's 2000x1815px and 171,786 bytes, and resized it to 1920x1742px in both Photoshop and grunt-responsive-images. I got the following output sizes:

* Photoshop, Save As…, PNG, interlaced: 174,144 bytes
* Photoshop, Save for Web & Devices…, PNG-24 (transparency, interlaced, convert to sRGB, preview use document profile, metadata none): 174,280 bytes
* grunt-responsive-images: 660,506 bytes

The above are the image sizes after all the images have been run through ImageOptim, but the grunt-responsive-images file was considerably larger than the others before that process too.

The settings for grunt-responsive-images were:

````
name: 'w1920',
width: 1920,
quality: 60,
aspectRatio: true,
upscale: true
````

These results are typical for all the PNGs I'm generating. Any idea why the grunt-produced images are so much larger than the Photoshop ones? I'm not super familiar with ImageMagick or GraphicsMagick, but I assume there must be some settings we can tweak to get better output.

All the images are attached below.

![procedural-manual-figure-2-en-w1920-gruntrespimg](https://cloud.githubusercontent.com/assets/786799/4686639/4807018a-5648-11e4-94d3-a4bf6a06cbae.png)
![procedural-manual-figure-2-en-w1920-pssaveas](https://cloud.githubusercontent.com/assets/786799/4686638/480223fe-5648-11e4-8289-77c5f7be2b26.png)
![procedural-manual-figure-2-en-w1920-pssaveforweb](https://cloud.githubusercontent.com/assets/786799/4686637/4801ed26-5648-11e4-8a67-a1a4f88e9b9b.png)
![procedural-manual-figure-2-en](https://cloud.githubusercontent.com/assets/786799/4686640/480af740-5648-11e4-8f8d-3af450b24e77.png)

**Comment by andismith** [comment]
I've added a option of sample. Set it to true to use sample.
