### ISSUE TITLE
GFX Engines objects wrong values?

### ISSUE THREAD

**Issue by YoungElPaso** [andismith/grunt-responsive-images#68]
Looks like the code and name values are inverted.  IE they're incorrectly referencing the OTHER library.

https://github.com/andismith/grunt-responsive-images/blob/master/tasks/responsive_images.js#L59

**Comment by andismith** [comment]
Looking it at this, this is actually correct.

They are in an 'alternative' object - so they are just used to show an alternative engine. I've fixed the indent so it's clearer.
