### ISSUE TITLE
Change default for jpeg quality to 80

### ISSUE THREAD

**Issue by aFarkas** [andismith/grunt-responsive-images#71]
Just realized that the default quality is 100, which is clearly to high. About 99% of all images for the web can be compressed with quality settings around 60-85. The best thing though would be an automatic compression. While I don't know anything in detail about jpeg compression, there are some interesting tools out there, that might be worth exploring. This should be related to issue #22:

- https://github.com/imagemin/imagemin-jpeg-recompress
- https://github.com/technopagan/adept-jpg-compressor
- https://github.com/rflynn/imgmin
- https://github.com/technopagan/cjpeg-dssim
- https://github.com/danielgtaylor/jpeg-archive

As a possible jpeg encoder you could use:
- https://github.com/mozilla/mozjpeg

**Comment by andismith** [comment]
Hi and thanks for your request,

It's out of scope of this task to also minify images. There are a number of tasks that already handle this such as https://github.com/gruntjs/grunt-contrib-imagemin

Simply run this task after Grunt Responsive Images.

I'm hesitant to change default values as it will give unexpected results for existing users who upgrade, but let's consider it for the next major version.

Thanks,
Andi

**Comment by aFarkas** [comment]
Unfortunately, I think most people won't realize this. Additionally this topic can become quite complex. There also seems to be a lot of misunderstanding in this field. For example grunt-contrib-imagemin does not compress images, it only removes metadata.

Using 100 for web as a default is always the wrong thing to do. As seen in your demo or in the demo of imager.js, no one is aware of the fact, that the default value is bad for the web. This said, while I don't think that you would break something in case you do set this to 80, the documentation should point out that in most cases this option should be lowered.

How bad this actually is can be just seen with your demo. Here is the compressed version of your wedding-large image. It was 455kb, now it is 65kb. You wedding-small image is 88kb. So for most people it is better to use right compression instead of resizing. 

![wedding-large](https://cloud.githubusercontent.com/assets/188254/5598036/d4055dc4-92ae-11e4-8a42-d36b07e78e41.jpg)
