### ISSUE TITLE
npm package contains tmp folder

### ISSUE THREAD

**Issue by benurb** [andismith/grunt-responsive-images#73]
Hello,

I just noticed that the currently released npm package (0.1.5) has a tmp folder inside, that is 13.8 MB large. Since it's not under version control here, I guess it shouldn't be there, but was present while publishing the package. Removing this subfolder would decrease the package size from 13.8 MB to 43.4 KB :grinning: 

Ben

**Comment by andismith** [comment]
This should be resolved now, thanks.
