### ISSUE TITLE
Added text to animated gif causes corrupt text on some frames.

### ISSUE THREAD

**Issue by MisterTea** [andismith/grunt-responsive-images#80]
Hey all,

I have this simple code that adds text to an animated gif: http://pastebin.com/AN5qpZWN

When I run it, I randomly get corrupt frames (see the attached source and output gif).  Notice that the text flickers on the output gif.

![chicken_regret_nothing](https://cloud.githubusercontent.com/assets/306879/6719034/3f155528-cd75-11e4-8751-c442c8519552.gif)

![chicken_regret_nothing_out](https://cloud.githubusercontent.com/assets/306879/6719037/42d2c2b8-cd75-11e4-8bf1-33477bb6abb5.gif)

**Comment by andismith** [comment]
The code you've supplied doesn't use Grunt Responsive Images.
This bug needs to be raised in the gm Git repo - https://github.com/aheckmann/gm

**Comment by MisterTea** [comment]
Sorry, I was on the wrong tab when I posted the issue
