### ISSUE TITLE
Task creates the same image multiple times if the destination is the same as the source

### ISSUE THREAD

**Issue by AurelioDeRosa** [andismith/grunt-responsive-images#91]
Hi there.

At the moment the task doesn't have any mechanism to recognize that it's processing the same image over and over again if the destination folder is the same as the source folder.

For example, in this configuration:

```js
responsive_images: {
    options: {
        engine: 'im',
        createNoScaledImage: true,
        sizes: [{
            name: 'mobile',
            width: 480
        }]
    },
    all: {
        files: [{
            expand: true,
            cwd: 'app/images/adverts',
            src: [
                '**/*.{gif,jpeg,jpg,png}',
                '!sprite/**/*.{gif,jpeg,jpg,png}'],
            dest: 'app/images/adverts'
        }]
    }
}
```

if I have the image `app/images/test.jpg`, after running the task the first time, it'll create `app/images/test-mobile.jpg`. If I run again the task, it'll create the image `app/images/test-mobile-mobile.jpg`, and so on.

It could be useful to detect if the image that is going to be create has the exact same size as the source, in which case the image isn't created.

**Comment by andismith** [comment]
I'm not sure why would you have the same source and destination folders?

Every time you recreate a JPG, you're introducing more and more artefacts as JPG is a lossy format. See http://improvephotography.com/2484/does-saving-a-jpeg-multiple-times-reduce-image-quality/

The idea is to have a base set of images in a separate folder which you'd resize from to ensure everything comes from the original source.

Anyway if you did want to have the same folder, you can do this in two steps:

1. To stop resizing `-mobile` images change your src to:
    src: [
        '**/*.{gif,jpeg,jpg,png}',
        '!**/*-mobile.{gif,jpeg,jpg,png}',
        '!sprite/**/*.{gif,jpeg,jpg,png}'],

2. To only resize new images use the option
    `newFilesOnly: true`

Alternatively, you could take the task out of the main workflow, so it's only run on demand.
