### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by benurb** [andismith/grunt-responsive-images#92]
Hey,

I just wanted to ask @andismith if you're still willing to maintain the project? It would be a shame if you're not, because it's a really handy tool in a lot of our build processes. Unfortunately though the backlog of pull requests and issues is increasing and there are a few problems that definitely need fixing. After we have discussed about it at my company for a while we started our own fork (especially because of the upscaling problem in #45 ). We would really like to switch back to upstream, but currently this is not possible. Do you have any updates for us about the future of the project?

Ben

**Comment by andismith** [comment]
Hi,

Yes, sorry. This project is still active - I just have been busy with other projects/work. I will try to assign some time this weekend to have a bit of a sort through and release a new version with a number of pull requests.

Thanks @benurb!
Andy

**Comment by benurb** [comment]
Hey Andy,

I'm glad to hear that! If you need help with something, just let me know :+1: 

Ben

**Comment by jhnns** [comment]
Thanks @andismith :+1:

**Comment by benurb** [comment]
May I kindly ask when you plan to push a new release to npm? :grinning:

**Comment by sjwilliams** [comment]
Hi @andismith. I'm following up on @benurb's question: do you know when you'll repub to NPM? We're hoping to take advantage of the huge speed increase in https://github.com/andismith/grunt-responsive-images/pull/93. We're getting about 5X (!) improvement on some of our current projects. Thx!

**Comment by andismith** [comment]
Hi, I've released v0.1.7 which includes these fixes, sorry for the delay!

**Comment by andismith** [comment]
I've done a quick release with the fixes that were easy to merge. I'll take a look at the others for a v0.1.8 release.

**Comment by sjwilliams** [comment]
Thanks @andismith, much appreciated!

**Comment by benurb** [comment]
Thank you very much Andi :+1:
