### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by cizza** [andismith/grunt-responsive-images#97]
Hi,
I have a problem with this plugin which was working for me just fine. It's not working anymore since I have created a folder in my assets/ folder which I was targeting with this plugin as a destination folder. The folder structure was:

/assets/images (src)
/assets/images-to-min (dest)

originaly the dest folder was in:

/images

The configuration of the plugin is :

responsive_images: {
		    myTask: {
		      options: {
		        sizes: [{
		          name: "",
		          width: 320
		        },{
		          name: "medium",
		          width: 640
		        },{
		          name: "large",
		          width: 1024,
		        }]
		      },
		      files: [{
		        expand: true,
		        src: ['**/*.{jpg,gif,png}'],
		        cwd: 'assets/images/',
		        dest: 'images/'
		      }]
		    }
	  },
watch: {
			
			images: {
				files: ['assets/images/**/*.{jpg,png,gif}'],
				tasks: ['responsive_images']
			}, //end of watch

		}

Well it is very strange problem because I am positive everything was working fine until I created that folder in the same directory as a the source image folder. When I retracted my code to the original version it still didn't work until I erased that new folder. Than it worked for a while and than zip. 

I was wondering if this plugin is caching anything? Than it would be possible to purge the cache and it might work again. 

Thanks

**Comment by cizza** [comment]
After more testing it seems to be a problem with the grunt-contrib-watch as I am able to run this task manually.

**Comment by andismith** [comment]
The `src` looks slightly wrong.

`src: ['*/.{jpg,gif,png}'],` should be `src: ['**/*.{jpg,gif,png}'],`

**Comment by andismith** [comment]
Did fixing the config solve the problem?

I'd like to close this issue please.
